### ISSUE TITLE
bug: typo in repo name

### ISSUE THREAD

**Issue by andy5995** [escottalexander/buidl-bots#1]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

@escottalexander I think there's a typo in your repo name! ;)

And hello!

### Expected Behavior

I think maybe the repo should be spelled "build" not "buidl"

### Steps To Reproduce

Reading.

**Comment by escottalexander** [comment]
Hey Andy! Thank you for submitting an issue. How are you doing? The funny thing is that the typo is intentional. It is a meme based off of another meme that was based on a very real typo. https://cryptowallet.com/glossary/buidl/

**Comment by andy5995** [comment]
Oh, well, I should have known YOU wouldn't make a mistake like that! :)

I'm hanging in there. How are you?

**Comment by escottalexander** [comment]
Haha, well, I am certainly not above mistakes. I am doing well. Good to hear from you!
